# Generated by Django 5.0.14 on 2026-09-02 13:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("cargo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("requisitos", models.TextField()),
                (
                    "salario",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("area_solicitante", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("interna", "Interna"), ("externa", "Externa")],
                        default="externa",
                        max_length=10,
                    ),
                ),
                (
                    "status_aprovacao",
                    models.CharField(
                        choices=[
                            ("aguardando_rh", "Aguardando aprovação do RH"),
                            ("aguardando_diretoria", "Aguardando aprovação da diretoria"),
                            ("aprovada", "Aprovada"),
                            ("reprovada", "Reprovada"),
                        ],
                        default="aguardando_rh",
                        max_length=25,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_andamento", "Em andamento"),
                            ("pausada", "Pausada"),
                            ("fechada", "Fechada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pausada",
                        max_length=15,
                    ),
                ),
                (
                    "custo_contratacao",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vagas_solicitadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoStatusVaga",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "tipo_status",
                    models.CharField(
                        choices=[("aprovacao", "Aprovação"), ("operacional", "Operacional")],
                        max_length=15,
                    ),
                ),
                ("de_status", models.CharField(blank=True, max_length=30)),
                ("para_status", models.CharField(max_length=30)),
                ("observacao", models.TextField(blank=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_status",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
