# Generated by Django 5.0.14 on 2026-09-03 18:29

import uuid

import django.db.models.deletion
from django.db import migrations, models

MODULOS = ["vagas", "candidatos", "processos-seletivos", "comunicacoes", "relatorios", "admissao"]


def criar_perfis_iniciais(apps, schema_editor):
    """Backfill: cada company_id existente ganha um perfil 'Administrador'
    (sistema, acesso total) para os usuários Gestor e um perfil 'Usuário
    Padrão' (personalizado, copiando as permissões já concedidas via
    UserFunctionPermission) para a equipe de RH. UserFunctionPermission
    continua sendo a fonte real do RBAC — isto só cria a camada descritiva
    de perfis por cima do que já existia.
    """
    Perfil = apps.get_model("core", "Perfil")
    PerfilFunctionPermission = apps.get_model("core", "PerfilFunctionPermission")
    User = apps.get_model("core", "User")
    UserFunctionPermission = apps.get_model("core", "UserFunctionPermission")

    company_ids = set(User.objects.filter(active=True).values_list("company_id", flat=True))

    for company_id in company_ids:
        gestores = User.objects.filter(company_id=company_id, active=True, role="gestor")
        if gestores.exists():
            admin_perfil = Perfil.objects.create(
                company_id=company_id,
                nome="Administrador",
                slug="administrador",
                descricao="Acesso total ao sistema.",
                tipo="sistema",
                ativo=True,
            )
            for modulo in MODULOS:
                PerfilFunctionPermission.objects.create(
                    perfil=admin_perfil,
                    company_id=company_id,
                    function=modulo,
                    can_view=True,
                    can_create=True,
                    can_edit=True,
                    can_delete=True,
                )
            gestores.update(perfil=admin_perfil)

        rh_users = list(User.objects.filter(company_id=company_id, active=True, role="rh"))
        if rh_users:
            padrao_perfil = Perfil.objects.create(
                company_id=company_id,
                nome="Usuário Padrão",
                slug="usuario-padrao",
                descricao="Perfil padrão da equipe de RH.",
                tipo="personalizado",
                ativo=True,
            )
            permissoes_existentes = {
                p.function: p for p in UserFunctionPermission.objects.filter(user=rh_users[0])
            }
            for modulo in MODULOS:
                base = permissoes_existentes.get(modulo)
                PerfilFunctionPermission.objects.create(
                    perfil=padrao_perfil,
                    company_id=company_id,
                    function=modulo,
                    can_view=bool(base and base.can_view),
                    can_create=bool(base and base.can_create),
                    can_edit=bool(base and base.can_edit),
                    can_delete=bool(base and base.can_delete),
                )
            for user in rh_users:
                user.perfil = padrao_perfil
                user.save(update_fields=["perfil"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("sistema", "Sistema"), ("personalizado", "Personalizado")],
                        default="personalizado",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PerfilFunctionPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "function",
                    models.SlugField(
                        help_text="Slug do módulo, ex: vagas, candidatos.", max_length=100
                    ),
                ),
                ("can_view", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="perfil",
            constraint=models.UniqueConstraint(
                fields=("company_id", "slug"), name="unique_perfil_slug_per_company"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="perfil",
            field=models.ForeignKey(
                blank=True,
                help_text="Perfil de acesso atribuído pelo Gestor; define as permissões por módulo.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="core.perfil",
            ),
        ),
        migrations.AddField(
            model_name="perfilfunctionpermission",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_permissions",
                to="core.perfil",
            ),
        ),
        migrations.AddConstraint(
            model_name="perfilfunctionpermission",
            constraint=models.UniqueConstraint(
                fields=("perfil", "function"), name="unique_perfil_function_permission"
            ),
        ),
        migrations.RunPython(criar_perfis_iniciais, migrations.RunPython.noop),
    ]
