# Generated by Django 5.0.14 on 2026-09-02 13:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidatos", "0001_initial"),
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessoSeletivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "etapa_atual",
                    models.CharField(
                        choices=[
                            ("triagem", "Triagem"),
                            ("teste", "Teste"),
                            ("entrevista", "Entrevista"),
                            ("proposta", "Proposta"),
                            ("contratado", "Contratado"),
                            ("reprovado", "Reprovado"),
                        ],
                        default="triagem",
                        max_length=15,
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to="candidatos.candidato",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="processoseletivo",
            constraint=models.UniqueConstraint(
                fields=("candidato", "vaga"), name="unique_candidato_vaga"
            ),
        ),
    ]
