# Generated by Django 5.0.14 on 2026-09-02 13:41

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(blank=True, max_length=128)),
                ("nome", models.CharField(blank=True, max_length=150)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("cargo_pretendido", models.CharField(blank=True, max_length=150)),
                (
                    "senioridade",
                    models.CharField(
                        blank=True,
                        choices=[("junior", "Júnior"), ("pleno", "Pleno"), ("senior", "Sênior")],
                        max_length=10,
                    ),
                ),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("resumo_experiencia", models.TextField(blank=True)),
                ("curriculo_bucket", models.CharField(blank=True, max_length=100)),
                ("curriculo_key", models.CharField(blank=True, max_length=255)),
                (
                    "curriculo_status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Processando"),
                            ("processado", "Processado"),
                            ("falha", "Falha"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("curriculo_erro", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="candidato",
            constraint=models.UniqueConstraint(
                fields=("company_id", "email"), name="unique_candidato_email"
            ),
        ),
    ]
