# Generated by Django 5.0.14 on 2026-09-02 14:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PontuacaoCandidato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("funcao", models.CharField(max_length=150)),
                ("pontuacao", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("manual", "Avaliação manual"),
                            ("motor_automatico", "Motor automático"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "detalhes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados do motor (ex: critérios, versão, prompt).",
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preenchido quando origem=manual; nulo quando origem=motor_automatico.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontuacoes",
                        to="candidatos.candidato",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
