# Generated by Django 5.0.14 on 2026-09-02 15:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidatos", "0002_pontuacaocandidato"),
        ("processos_seletivos", "0002_avaliacaoprocesso_entrevistaagendamento_and_more"),
        ("vagas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("cargo", models.CharField(blank=True, max_length=150)),
                ("data_admissao", models.DateField(blank=True, null=True)),
                (
                    "status_onboarding",
                    models.CharField(
                        choices=[
                            ("documentos_pendentes", "Documentos pendentes"),
                            ("em_analise", "Em análise"),
                            ("concluido", "Concluído"),
                        ],
                        default="documentos_pendentes",
                        max_length=25,
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissoes",
                        to="candidatos.candidato",
                    ),
                ),
                (
                    "processo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funcionario",
                        to="processos_seletivos.processoseletivo",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissoes",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItemAdmissao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("nome_documento", models.CharField(max_length=150)),
                ("obrigatorio", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("enviado", "Enviado"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("documento_bucket", models.CharField(blank=True, max_length=100)),
                ("documento_key", models.CharField(blank=True, max_length=255)),
                ("observacao", models.TextField(blank=True)),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="admissao.funcionario",
                    ),
                ),
            ],
            options={
                "ordering": ["nome_documento"],
            },
        ),
    ]
